### ISSUE TITLE
yyy,  в одну строчку же можно...

### ISSUE THREAD

**Issue by woainikk** [AntipovAndrey/Intellij-search-plugin#1]
https://github.com/AntipovAndrey/Intellij-search-plugin/blob/43f8fdf9785ff8b3c16cbe1766afdbbae15064b4/src/main/kotlin/ru/andrey/settings/SearchEngineConfig.kt#L16

**Comment by AntipovAndrey** [comment]
Можно
Не вижу преимуществ
Особенно для переопределений
